# Generated by Django 2.1 on 2019-04-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='book_img/')),
                ('pdf', models.FileField(upload_to='file_pdf/')),
                ('summary', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('due_back', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='authers',
            name='img',
            field=models.ImageField(default=1, upload_to='auther_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authers',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
