# Generated by Django 2.1 on 2019-04-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_books_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='authers',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
