# Generated by Django 2.1 on 2019-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_authers_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authers',
            options={'ordering': ['-date_of_publication']},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-date_of_publication']},
        ),
        migrations.RenameField(
            model_name='books',
            old_name='due_back',
            new_name='date_of_publication',
        ),
        migrations.AddField(
            model_name='authers',
            name='date_of_publication',
            field=models.DateField(auto_now=True),
        ),
    ]
