# Generated by Django 2.1 on 2019-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190416_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='famous_books',
            field=models.BooleanField(default=False),
        ),
    ]
