# Generated by Django 2.1 on 2019-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(default=1, upload_to='team_img/'),
            preserve_default=False,
        ),
    ]
