# Generated by Django 2.1 on 2019-04-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190420_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='auther',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Authers',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
