# Generated by Django 2.1 on 2019-04-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190420_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='tags',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
